version: '3'

services:
  fastapi:
    container_name: fast_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.eatables.com.br/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/api.eatables.com.br/privkey.pem:/etc/ssl/private/privkey.pem:ro
    ports:
      - "443:443"
